/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp2;

import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author ayusudi
 */
public class FormCreatePatient extends javax.swing.JInternalFrame {

        /**
         * Creates new form FormCreatePatient
         */
        public FormCreatePatient() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                nama = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                nik = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                tanggal = new com.toedter.calendar.JDateChooser();
                java.sql.Date sqlDate = java.sql.Date.valueOf("2000-01-01");
                java.util.Date utilDate = new java.util.Date(sqlDate.getTime());
                tanggal.setDate(utilDate);
                jLabel5 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                alamat = new javax.swing.JTextArea();
                submit = new javax.swing.JButton();

                addAncestorListener(new javax.swing.event.AncestorListener() {
                        public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                        }

                        public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                        }

                        public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                                formAncestorRemoved(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
                jLabel1.setText(" FORMULIR DATA PASIEN");
                jLabel1.setToolTipText("");

                nama.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                namaActionPerformed(evt);
                        }
                });

                jLabel2.setText("NAMA      :");

                jLabel3.setText("NIK          :");

                jLabel4.setText("TGL LAHIR : ");

                tanggal.setDateFormatString("YYYY-MMM-dd");

                jLabel5.setText("ALAMAT :");

                alamat.setColumns(20);
                alamat.setRows(5);
                jScrollPane1.setViewportView(alamat);

                submit.setText("Submit");
                submit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                submitActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(75, 75, 75)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(tanggal,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel5,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                113,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(253, 253, 253))
                                                                                .addComponent(jScrollPane1)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(nik)
                                                                                                                .addComponent(nama)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(submit,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                101,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addGap(75, 75, 75))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(107, 107, 107)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(106, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(jLabel1)
                                                                .addGap(37, 37, 37)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.CENTER)
                                                                                .addComponent(nama,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                27, Short.MAX_VALUE)
                                                                                .addComponent(jLabel2))
                                                                .addGap(34, 34, 34)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(nik,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(34, 34, 34)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(tanggal,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jLabel5)
                                                                .addGap(7, 7, 7)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(submit)
                                                                .addContainerGap(86, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void namaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_namaActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_namaActionPerformed

        private void submitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitActionPerformed
                // TODO add your handling code here:
                String inputNama = nama.getText();
                String inputNIK = nik.getText();

                SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");

                String inputTanggal = String.valueOf(fm.format(tanggal.getDate()));

                String inputAlamat = alamat.getText();
                System.out.println(inputNama);
                System.out.println(inputNIK);
                System.out.println(inputTanggal);
                System.out.println(inputAlamat);
                ArrayList<String> errors = TP2.validasi(inputNama, inputNIK, inputTanggal, inputAlamat);
                if (errors.size() > 0) {
                        JOptionPane.showMessageDialog(this, errors);
                } else {
                        try {
                                // Execute query INSERT to table patients
                                String query = "INSERT INTO patients (nama, alamat, nik, tanggal_lahir) VALUES ('"
                                                + inputNama + "','"
                                                + inputAlamat + "','" + inputNIK + "','" + inputTanggal + "');";
                                JdbcConn.connection.createStatement().execute(query);
                                TP2.page = "Home";
                                this.dispose();
                        } catch (SQLException e) {
                                String pesan = e.getMessage();
                                if (e.getMessage().contains("nama_key")) {
                                        pesan = "Nama '" + inputNama + "' sudah terdaftar.";
                                } else if (e.getMessage().contains("nik_key")) {
                                        pesan = "NIK '" + inputNIK + "' sudah terdaftar.";
                                }
                                JOptionPane.showMessageDialog(this, pesan);
                        }

                }

        }// GEN-LAST:event_submitActionPerformed

        private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_formAncestorRemoved
                // TODO add your handling code here:
        }// GEN-LAST:event_formAncestorRemoved

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextArea alamat;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField nama;
        private javax.swing.JTextField nik;
        private javax.swing.JButton submit;
        private com.toedter.calendar.JDateChooser tanggal;
        // End of variables declaration//GEN-END:variables
}
