/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2;

import java.awt.event.ComponentEvent;
import tp2.JdbcConn;
import java.util.ArrayList;

/**
 *
 * @author Naratama
 */
public class TP2 extends javax.swing.JFrame {

    /**
     * Creates new form TP2
     */
    static public String page = "Home";

    public TP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        DesktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        mainButton = new javax.swing.JButton();
        closeApp = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DesktopPaneComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                DesktopPaneComponentRemoved(evt);
            }
        });
        DesktopPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                DesktopPaneAncestorRemoved(evt);
            }
        });
        DesktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DesktopPaneComponentShown(evt);
            }
        });
        TablePatient table = new TablePatient();
        table.setVisible(true);
        DesktopPane.add(table);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("SOAL 3 : APLIKASI CRUD PASIEN");

        mainButton.setText("Tambah Pasien");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        closeApp.setBackground(new java.awt.Color(0, 51, 51));
        closeApp.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        closeApp.setForeground(new java.awt.Color(153, 204, 255));
        closeApp.setText("exit");
        closeApp.setMaximumSize(new java.awt.Dimension(24, 24));
        closeApp.setMinimumSize(new java.awt.Dimension(24, 24));
        closeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(mainButton)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAppActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeAppActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_closeAppActionPerformed

    private void DesktopPaneAncestorRemoved(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_DesktopPaneAncestorRemoved
        // TODO add your handling code here:

    }// GEN-LAST:event_DesktopPaneAncestorRemoved

    private void DesktopPaneComponentRemoved(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_DesktopPaneComponentRemoved
        // TODO add your handling code here:
    }// GEN-LAST:event_DesktopPaneComponentRemoved

    public void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (page == "Home") {
            page = "FormCreate";
        } else {
            page = "Home";
        }
        if (this.DesktopPane.getComponentCount() > 0) {
            this.DesktopPane.getComponent(0).setVisible(false);
            this.DesktopPane.remove(this.DesktopPane.getComponent(0));
        }
        // if (mainButton.getText() == "Kembali") {
        // TableDataPatient table = new TableDataPatient();
        // table.setVisible(true);
        // this.DesktopPane.add(table);
        // page = "Home";

        // mainButton.setText("Tambah Pasien");
        // } else {
        // FormCreatePatient dataForm = new FormCreatePatient();
        // dataForm.setVisible(true);
        // this.DesktopPane.add(dataForm);
        // mainButton.setText("Kembali");

        // dataForm.addComponentListener(new java.awt.event.ComponentAdapter() {
        // public void componentHidden(ComponentEvent e) {
        // TP2.this.mainButtonActionPerformed(evt);
        // page = "Home";
        // }
        // });
        // }
    }

    private void DesktopPaneComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_DesktopPaneComponentShown
        // TODO add your handling code here:

    }// GEN-LAST:event_DesktopPaneComponentShown

    private void DesktopPaneComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_DesktopPaneComponentAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_DesktopPaneComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            JdbcConn.main(args);
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception e) {
            System.out.print(e);
        }
        // </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP2().setVisible(true);
            }
        });
    }

    public static ArrayList<String> validasi(String inputNama, String inputNIK, String inputTanggal,
            String inputAlamat) {
        ArrayList<String> errors = new ArrayList<String>();
        if (inputNama.length() == 0) {
            errors.add("Nama harus di isi!");
        }
        if (inputNIK.length() != 15) {
            errors.add("NIK harus di 15 character");
        }

        if (inputNIK.length() > 0) {
            boolean allDigit = true;
            for (int i = 0; i < inputNIK.length(); i++) {
                if (!Character.isDigit(inputNIK.charAt(i))) {
                    allDigit = false;
                }
            }
            if (!allDigit) {
                errors.add("NIK terdiri dari character numeric");
            }
        }
        if (inputTanggal.length() == 0) {
            errors.add("Nama harus di isi!");
        }
        if (inputAlamat.length() == 0) {
            errors.add("Nama harus di isi!");
        }
        return errors;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton closeApp;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainButton;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
